name:                logging
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gbwey/logging#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - clock
  - deepseq
  - dhall >= 1.32.0
  - directory
  - either
  - extra
  - fast-logger
  - formatting
  - iso8601-time
  - lens
  - lens-datetime
  - mime-mail
  - monad-logger
  - mtl
  - shakespeare
  - smtp-mail
  - template-haskell
  - text
  - time
  - unix-time
  - unliftio
  - unliftio-core
when:
    - condition: os(windows)
      dependencies: Win32 >= 2.2 && < 2.9

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  when:
     condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie
     - -Widentities

executables:
  perflog:
    source-dirs:
    - app
    main:             Main.hs
    ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
       - -Widentities
    dependencies:
    - base
    - logging
    - criterion

tests:
  logging-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
       - -Widentities
    dependencies:
    - base
    - logging
    - tasty
    - tasty-hunit
